Sprint 7 solution in file manager
OlgaBulavina/java-kanban pull request #4
Opened 2024-07-06 14:52 UTC by OlgaBulavina

2024-07-07 04:02 UTC, EugeneLenkevich requested changes
Привет, Оля, спасибо за присланное решение

Все верно, единственное непроверяемые исключения не надо перехватывать, их смысл как раз в том чтобы сигнализировать о непредвиденных ситуациях, это как чек энджин на приборной панели :)

2024-07-07 04:02 UTC, EugeneLenkevich commented on src/model/Subtask.java
> +    private static TaskType subtaskType = TaskType.SUBTASK;
А зачем, кстати, эти статические переменные, не проще сразу из getTaskType возвращать нужный тип :)

2024-07-07 04:02 UTC, EugeneLenkevich commented on src/service/FileBackedTaskManager.java
> +        } catch (ManagerSaveException e) {
Не надо перехватывать ManagerSaveException, пусть приложение валится :)
Если файл не удалось прочитать по какой либо причине, то приложение скорее всего находится в неизвестном или неконсистентном состоянии. Лучше сразу упасть чтобы пользователь знал что что-то пошло не так 

https://habr.com/ru/post/218325/

2024-07-07 04:02 UTC, EugeneLenkevich commented on test/service/FileBackedTaskManagerTest.java
> +        ArrayList tasks = fileBackedTaskManager.showAllTasks();
List tasks = ...

А давай подобных местах сделаем интерфейс, а не конкретную реализацию :)

2024-07-08 11:41 UTC, OlgaBulavina commented on src/model/Subtask.java
> +    private static TaskType subtaskType = TaskType.SUBTASK;
точно))

2024-07-08 12:05 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2024-07-09 15:57 UTC, merged